//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRAFrontend.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRAFrontend.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ActivityText {
            get {
                return ResourceManager.GetString("ActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string AdvanceText {
            get {
                return ResourceManager.GetString("AdvanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all configurations.
        /// </summary>
        public static string AllButtonTipText {
            get {
                return ResourceManager.GetString("AllButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Notification.
        /// </summary>
        public static string AllowNotificationText {
            get {
                return ResourceManager.GetString("AllowNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Channel.
        /// </summary>
        public static string AppChannelText {
            get {
                return ResourceManager.GetString("AppChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data folder.
        /// </summary>
        public static string AppDataFolder {
            get {
                return ResourceManager.GetString("AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code.
        /// </summary>
        public static string AuthorCodeText {
            get {
                return ResourceManager.GetString("AuthorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string AutoUpdateText {
            get {
                return ResourceManager.GetString("AutoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download and unzip when updates are available.
        /// </summary>
        public static string AutoUpdateTipText {
            get {
                return ResourceManager.GetString("AutoUpdateTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Opacity.
        /// </summary>
        public static string BackgroundImageOpacityText {
            get {
                return ResourceManager.GetString("BackgroundImageOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImageText {
            get {
                return ResourceManager.GetString("BackgroundImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend logs folder.
        /// </summary>
        public static string BeLogsFolderText {
            get {
                return ResourceManager.GetString("BeLogsFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the image path.
        /// </summary>
        public static string BgImagePathWatermarkText {
            get {
                return ResourceManager.GetString("BgImagePathWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string CheckForUpdateText {
            get {
                return ResourceManager.GetString("CheckForUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronicle.
        /// </summary>
        public static string ChronicleText {
            get {
                return ResourceManager.GetString("ChronicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Recognition Confidence.
        /// </summary>
        public static string ConfidenceText {
            get {
                return ResourceManager.GetString("ConfidenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a config name.
        /// </summary>
        public static string ConfigInputMarkText {
            get {
                return ResourceManager.GetString("ConfigInputMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs folder.
        /// </summary>
        public static string ConfigsFolder {
            get {
                return ResourceManager.GetString("ConfigsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ConsoleText {
            get {
                return ResourceManager.GetString("ConsoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel Opacity.
        /// </summary>
        public static string ControlPanelOpacityText {
            get {
                return ResourceManager.GetString("ControlPanelOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic Strife.
        /// </summary>
        public static string CosmicStrifeText {
            get {
                return ResourceManager.GetString("CosmicStrifeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a desktop shortcut.
        /// </summary>
        public static string CreateShortcutText {
            get {
                return ResourceManager.GetString("CreateShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the currently selected config.
        /// </summary>
        public static string CurrentButtonTipText {
            get {
                return ResourceManager.GetString("CurrentButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentText {
            get {
                return ResourceManager.GetString("CurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkText {
            get {
                return ResourceManager.GetString("DarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Start Page.
        /// </summary>
        public static string DefaultPageText {
            get {
                return ResourceManager.GetString("DefaultPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Nofication.
        /// </summary>
        public static string EmailNotificationText {
            get {
                return ResourceManager.GetString("EmailNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray icon.
        /// </summary>
        public static string EnableTrayIconText {
            get {
                return ResourceManager.GetString("EnableTrayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure.
        /// </summary>
        public static string EnsureText {
            get {
                return ResourceManager.GetString("EnsureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtensionText {
            get {
                return ResourceManager.GetString("ExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend logs folder.
        /// </summary>
        public static string FeLogsFolder {
            get {
                return ResourceManager.GetString("FeLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        public static string FollowSystemText {
            get {
                return ResourceManager.GetString("FollowSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open On GitHub.
        /// </summary>
        public static string GithubToolTipText {
            get {
                return ResourceManager.GetString("GithubToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SRA.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string GuideText {
            get {
                return ResourceManager.GetString("GuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys in Game.
        /// </summary>
        public static string HotkeysText {
            get {
                return ResourceManager.GetString("HotkeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the End.
        /// </summary>
        public static string InTheEndText {
            get {
                return ResourceManager.GetString("InTheEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightText {
            get {
                return ResourceManager.GetString("LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapText {
            get {
                return ResourceManager.GetString("MapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chyan.
        /// </summary>
        public static string MirrorChyanText {
            get {
                return ResourceManager.GetString("MirrorChyanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chyan‘s high-speed download service.
        /// </summary>
        public static string MirrorChyanTipText {
            get {
                return ResourceManager.GetString("MirrorChyanTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to modify.
        /// </summary>
        public static string ModifyHoldText {
            get {
                return ResourceManager.GetString("ModifyHoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New config.
        /// </summary>
        public static string NewConfigText {
            get {
                return ResourceManager.GetString("NewConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string NotSetText {
            get {
                return ResourceManager.GetString("NotSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string ReceiverEmailAddrText {
            get {
                return ResourceManager.GetString("ReceiverEmailAddrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Rewards.
        /// </summary>
        public static string ReceiveRewardsText {
            get {
                return ResourceManager.GetString("ReceiveRewardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string RegularText {
            get {
                return ResourceManager.GetString("RegularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current config.
        /// </summary>
        public static string RemoveConfigText {
            get {
                return ResourceManager.GetString("RemoveConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource integrity check.
        /// </summary>
        public static string ResourceIntegrityCheckText {
            get {
                return ResourceManager.GetString("ResourceIntegrityCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data only without running.
        /// </summary>
        public static string SaveOnlyButtonTipText {
            get {
                return ResourceManager.GetString("SaveOnlyButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Only.
        /// </summary>
        public static string SaveOnlyText {
            get {
                return ResourceManager.GetString("SaveOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string SenderEmailAddrText {
            get {
                return ResourceManager.GetString("SenderEmailAddrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SettingText {
            get {
                return ResourceManager.GetString("SettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SmtpPortText {
            get {
                return ResourceManager.GetString("SmtpPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        public static string SmtpServerText {
            get {
                return ResourceManager.GetString("SmtpServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Settings.
        /// </summary>
        public static string SmtpSettingsText {
            get {
                return ResourceManager.GetString("SmtpSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string SponsorText {
            get {
                return ResourceManager.GetString("SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the task in the current mode.
        /// </summary>
        public static string StartButtonTipText {
            get {
                return ResourceManager.GetString("StartButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGameText {
            get {
                return ResourceManager.GetString("StartGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Up.
        /// </summary>
        public static string StartUpText {
            get {
                return ResourceManager.GetString("StartUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Hotkey.
        /// </summary>
        public static string StopHotkeyText {
            get {
                return ResourceManager.GetString("StopHotkeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Notification.
        /// </summary>
        public static string SystemNotificationText {
            get {
                return ResourceManager.GetString("SystemNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Settings.
        /// </summary>
        public static string TaskSettingsText {
            get {
                return ResourceManager.GetString("TaskSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        public static string TechniqueText {
            get {
                return ResourceManager.GetString("TechniqueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Safety.
        /// </summary>
        public static string ThreadSafetyText {
            get {
                return ResourceManager.GetString("ThreadSafetyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailblaze Power.
        /// </summary>
        public static string TrailblazePowerText {
            get {
                return ResourceManager.GetString("TrailblazePowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannelText {
            get {
                return ResourceManager.GetString("UpdateChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        public static string WarpText {
            get {
                return ResourceManager.GetString("WarpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Official Webside.
        /// </summary>
        public static string WebsideToolTipText {
            get {
                return ResourceManager.GetString("WebsideToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomText {
            get {
                return ResourceManager.GetString("ZoomText", resourceCulture);
            }
        }
    }
}
