//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRAFrontend.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRAFrontend.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string AdvanceText {
            get {
                return ResourceManager.GetString("AdvanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Notification.
        /// </summary>
        public static string AllowNotificationText {
            get {
                return ResourceManager.GetString("AllowNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Channel.
        /// </summary>
        public static string AppChannelText {
            get {
                return ResourceManager.GetString("AppChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string AutoUpdateText {
            get {
                return ResourceManager.GetString("AutoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Opacity.
        /// </summary>
        public static string BackgroundImageOpacityText {
            get {
                return ResourceManager.GetString("BackgroundImageOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImageText {
            get {
                return ResourceManager.GetString("BackgroundImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Recognition Confidence.
        /// </summary>
        public static string ConfidenceText {
            get {
                return ResourceManager.GetString("ConfidenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkText {
            get {
                return ResourceManager.GetString("DarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Start Page.
        /// </summary>
        public static string DefaultPageText {
            get {
                return ResourceManager.GetString("DefaultPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray icon.
        /// </summary>
        public static string EnableTrayIconText {
            get {
                return ResourceManager.GetString("EnableTrayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtensionText {
            get {
                return ResourceManager.GetString("ExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        public static string FollowSystemText {
            get {
                return ResourceManager.GetString("FollowSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open On GitHub.
        /// </summary>
        public static string GithubToolTipText {
            get {
                return ResourceManager.GetString("GithubToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SRA.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightText {
            get {
                return ResourceManager.GetString("LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogText {
            get {
                return ResourceManager.GetString("LogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chyan.
        /// </summary>
        public static string MirrorChyanText {
            get {
                return ResourceManager.GetString("MirrorChyanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string RegularText {
            get {
                return ResourceManager.GetString("RegularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource integrity check.
        /// </summary>
        public static string ResourceIntegrityCheckText {
            get {
                return ResourceManager.GetString("ResourceIntegrityCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SettingText {
            get {
                return ResourceManager.GetString("SettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string SponsorText {
            get {
                return ResourceManager.GetString("SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Up.
        /// </summary>
        public static string StartUpText {
            get {
                return ResourceManager.GetString("StartUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Settings.
        /// </summary>
        public static string TaskSettingsText {
            get {
                return ResourceManager.GetString("TaskSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Safety.
        /// </summary>
        public static string ThreadSafetyText {
            get {
                return ResourceManager.GetString("ThreadSafetyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannelText {
            get {
                return ResourceManager.GetString("UpdateChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Official Webside.
        /// </summary>
        public static string WebsideToolTipText {
            get {
                return ResourceManager.GetString("WebsideToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomText {
            get {
                return ResourceManager.GetString("ZoomText", resourceCulture);
            }
        }
    }
}
