[subtasks.ornament_extraction]
name = "饰品提取"
func = "ornament_extraction"
cost = 40
max_count = 6
levels = [
    { id = 14, name = "placeholder", result = "坠星启航地/寰宇生研院" },
    { id = 1, name = "鎏金追忆", result = "零号关卡朋克洛德/千星荟萃之城" },
    { id = 2, name = "西风丛中", result = "永恒之地翁法罗斯/天国@直播间" },
    { id = 3, name = "月下朱殷", result = "妖精织梦的乐园/沉欢醉饮的海隅" },
    { id = 4, name = "纷争不休", result = "谧宁拾骨地/渊思寂虑的巨树" },
    { id = 5, name = "蠹役饥肠", result = "沉陆海域露莎卡/奇想蕉乐园" },
    { id = 6, name = "永恒笑剧", result = "奔狼的都蓝王朝/劫火莲灯铸炼宫" },
    { id = 7, name = "伴你入眠", result = "无主荒星茨冈尼亚/出云显世与高天神国" },
    { id = 8, name = "天剑如雨", result = "苍穹战线格拉默/梦想之地匹诺康尼" },
    { id = 9, name = "孽果盘生", result = "繁星竞技场/折断的龙骨" },
    { id = 10, name = "百年冻土", result = "筑城者的贝洛伯格/停转的萨尔索图" },
    { id = 11, name = "温柔话语", result = "泛银河商业公司/星体差分机" },
    { id = 12, name = "浴火钢心", result = "盗贼公国塔利亚/生命的翁瓦克" },
    { id = 13, name = "坚城不倒", result = "太空封印站/不老者的仙舟" }
]

[subtasks.calyx_golden]
name = "拟造花萼（金）"
func = "calyx_golden"
cost = 10
max_count = 24
levels = [
    { id = 1, name = "回忆之蕾（二相乐园）", result = "漫游指南" },
    { id = 2, name = "以太之蕾（二相乐园）", result = "提纯以太" },
    { id = 3, name = "珍藏之蕾（二相乐园）", result = "信用点" },
    { id = 4, name = "回忆之蕾（翁法罗斯）", result = "漫游指南" },
    { id = 5, name = "以太之蕾（翁法罗斯）", result = "提纯以太" },
    { id = 6, name = "珍藏之蕾（翁法罗斯）", result = "信用点" },
    { id = 7, name = "回忆之蕾（匹诺康尼）", result = "漫游指南" },
    { id = 8, name = "以太之蕾（匹诺康尼）", result = "提纯以太" },
    { id = 9, name = "珍藏之蕾（匹诺康尼）", result = "信用点" },
    { id = 10, name = "回忆之蕾（仙舟罗浮）", result = "漫游指南" },
    { id = 11, name = "以太之蕾（仙舟罗浮）", result = "提纯以太" },
    { id = 12, name = "珍藏之蕾（仙舟罗浮）", result = "信用点" },
    { id = 13, name = "回忆之蕾（雅利洛VI）", result = "漫游指南" },
    { id = 14, name = "以太之蕾（雅利洛VI）", result = "提纯以太" },
    { id = 15, name = "珍藏之蕾（雅利洛VI）", result = "信用点" }
]

[subtasks.calyx_crimson]
name = "拟造花萼（赤）"
func = "calyx_crimson"
cost = 10
max_count = 24
levels = [
    { id = 1, name = "万色，愚者自将（毁灭）", result = "万色，愚者自将" },
    { id = 2, name = "月狂獠牙（毁灭）", result = "月狂獠牙" },
    { id = 3, name = "净世残刃（毁灭）", result = "净世残刃" },
    { id = 4, name = "神体琥珀（存护）", result = "神体琥珀" },
    { id = 5, name = "琥珀的坚守（存护）", result = "琥珀的坚守" },
    { id = 6, name = "天谴血矛（巡猎）", result = "天谴血矛" },
    { id = 7, name = "逆时一击（巡猎）", result = "逆时一击" },
    { id = 8, name = "逐星之矢（巡猎）", result = "逐星之矢" },
    { id = 9, name = "万相果实（丰饶）", result = "万相果实" },
    { id = 10, name = "永恒之花（丰饶）", result = "永恒之花" },
    { id = 11, name = "银河沙盘（智识）", result = "银河沙盘" },
    { id = 12, name = "精致色稿（智识）", result = "精致色稿" },
    { id = 13, name = "智识之钥（智识）", result = "智识之钥" },
    { id = 14, name = "天外乐章（同谐）", result = "天外乐章" },
    { id = 15, name = "群星乐章（同谐）", result = "群星乐章" },
    { id = 16, name = "法吉娜之心（虚无）", result = "法吉娜之心" },
    { id = 17, name = "焚天之魔（虚无）", result = "焚天之魔" },
    { id = 18, name = "沉沦黑曜（虚无）", result = "沉沦黑曜" },
    { id = 19, name = "阿赖耶华（记忆）", result = "阿赖耶华" },
    { id = 20, name = "《绒绒号》典藏版合集（欢愉）", result = "《绒绒号》典藏版合集" }
]

[subtasks.stagnant_shadow]
name = "凝滞虚影"
func = "stagnant_shadow"
cost = 30
max_count = 8
levels = [
    { id = 1, name = "溟簇之形", result = "侵略凝块" },
    { id = 2, name = "职司之形", result = "星际和平工作证" },
    { id = 3, name = "幽府之形", result = "幽府通令" },
    { id = 4, name = "锋芒之形", result = "铁狼碎齿" },
    { id = 5, name = "残灰之形", result = "明辉日珥" },
    { id = 6, name = "嗔怒之形", result = "忿火之心" },
    { id = 7, name = "燔灼之形", result = "过热钢刃" },
    { id = 8, name = "炎华之形", result = "恒温晶壳" },
    { id = 9, name = "塞壬之形", result = "海妖残鰭" },
    { id = 10, name = "冰酿之形", result = "冷藏梦箱" },
    { id = 11, name = "冰棱之形", result = "苦寒晶壳" },
    { id = 12, name = "霜晶之形", result = "风雪之角" },
    { id = 13, name = "音爆之形", result = "狂雷扫弦" },
    { id = 14, name = "机狼之形", result = "兽棺之钉" },
    { id = 15, name = "震厄之形", result = "炼形者雷枝" },
    { id = 16, name = "鸣雷之形", result = "往日之影的雷冠" },
    { id = 17, name = "烬日之形", result = "暮辉烬蕾" },
    { id = 18, name = "今宵之形", result = "一杯酪酊的时代" },
    { id = 19, name = "天人之形", result = "无人遗垢" },
    { id = 20, name = "巽风之形", result = "暴风之眼" },
    { id = 21, name = "吞噬之形", result = "嗤笑丑面" },
    { id = 22, name = "凛月之形", result = "暗帷月华" },
    { id = 23, name = "焦炙之形", result = "炙梦喷枪" },
    { id = 24, name = "孽兽之形", result = "苍猿之钉" },
    { id = 25, name = "空海之形", result = "虚幻铸铁" },
    { id = 26, name = "役轮之形", result = "纷争先兆" },
    { id = 27, name = "弦音之形", result = "一曲合弦的幻景" },
    { id = 28, name = "偃偶之形", result = "镇灵敕符" },
    { id = 29, name = "幻光之形", result = "往日之影的金饰" }
]

[subtasks.caver_of_corrosion]
name = "侵蚀隧洞"
func = "caver_of_corrosion"
cost = 40
max_count = 6
levels = [
    { id = 1, name = "观火之径", result = "星如我见的领航员/叩问天工的名冶" },
    { id = 2, name = "魔占之径", result = "闪耀功勋的魔法少女/应天涉远的卜者" },
    { id = 3, name = "隐救之径", result = "再创天地的救世主/自匿星芒的隐士" },
    { id = 4, name = "雳勇之径", result = "烈阳惊雷的女武神/恶海逐波的船长" },
    { id = 5, name = "弦歌之径", result = "凯歌祝捷的英豪/哀歌覆国的诗人" },
    { id = 6, name = "迷识之径", result = "重循苦旅的司铎/识海迷坠的学者" },
    { id = 7, name = "勇骑之径", result = "荡除蠹灾的铁骑/风举云飞的勇烈" },
    { id = 8, name = "梦潜之径", result = "死水深潜的先驱/机心戏梦的钟表匠" },
    { id = 9, name = "幽冥之径", result = "毁烬焚骨的大公/幽锁深牢的系囚" },
    { id = 10, name = "药使之径", result = "宝命长存的莳者/骇域漫游的信使" },
    { id = 11, name = "野焰之径", result = "熔岩锻铸的火匠/盗匪荒漠的废土客" },
    { id = 12, name = "圣颂之径", result = "净庭教宗的圣骑士/激奏雷电的乐队" },
    { id = 13, name = "睿智之径", result = "戍卫风雪的铁卫/繁星璀璨的天才" },
    { id = 14, name = "漂泊之径", result = "云无留迹的过客/野穗伴行的快枪手" },
]

[subtasks.echo_of_war]
name = "历战余响"
func = "echo_of_war"
cost = 30
max_count = 3
levels = [
    { id = 1, name = "伪觉者的期许", result = "伪觉者的期许" },
    { id = 2, name = "灭流绝溢的缄默", result = "灭流绝溢的缄默" },
    { id = 3, name = "阳雷的遥想", result = "阳雷的遥想" },
    { id = 4, name = "吉光片羽", result = "吉光片羽" },
    { id = 5, name = "同愿的遗音", result = "同愿的遗音" },
    { id = 6, name = "蛀星孕灾的旧恶", result = "蛀星孕灾的旧恶" },
    { id = 7, name = "无穷假身的遗恨", result = "无穷假身的遗恨" },
    { id = 8, name = "守护者的悲愿", result = "守护者的悲愿" },
    { id = 9, name = "毁灭者的末路", result = "毁灭者的末路" }
]