class SRAFileType:
    HEADER_MAGIC = ...
    CONTENT_MAGIC = ...

    def __init__(self, content, version=1):...

    def write(self, filepath)->None:...

    @staticmethod
    def save(content, filepath, version=1)->None:...

    @classmethod
    def load(cls, filepath):...

