# ==================== 图片常量集中管理 ====================
# 说明：集中管理所有在本模块使用的图片路径，避免散落的硬编码字符串，方便统一修改与查找。
# 分组：通用 IMG（跨模式通用），货币战争专用 CWIMG。

class IMG:
    ENTER = "resources/img/enter.png"
    F4 = "resources/img/f4.png"
    COLLECTION = "resources/img/collection.png"
    ENSURE = "resources/img/ensure.png"
    ENSURE2 = "resources/img/ensure2.png"


class CWIMG:
    BASE = "resources/img/currency_wars"
    CURRENCY_WARS_START = f"{BASE}/currency_wars_start.png"
    PREPARATION_STAGE = f"{BASE}/preparation_stage.png"
    ENTER_STANDARD = f"{BASE}/enter_standard.png"
    CONTINUE_PROGRESS = f"{BASE}/continue_progress.png"
    DOWN_ARROW = f"{BASE}/down_arrow.png"
    START_GAME = f"{BASE}/start_game.png"
    NEXT_STEP = f"{BASE}/next_step.png"
    INVEST_ENVIRONMENT = f"{BASE}/invest_environment.png"
    CLICK_BLANK = f"{BASE}/click_blank.png"
    STRATEGY = f"{BASE}/strategy.png"
    CANCEL_APPLY = f"{BASE}/cancel_apply.png"
    APPLY = f"{BASE}/apply.png"
    TRACE = f"{BASE}/trace.png"
    OPEN = f"{BASE}/open.png"
    SETTLE = f"{BASE}/settle.png"
    CONTINUE = f"{BASE}/continue.png"
    REPLENISH_STAGE = f"{BASE}/replenish_stage.png"
    ENCOUNTER_NODE = f"{BASE}/encounter_node.png"
    FOLD = f"{BASE}/fold.png"
    SELECT_INVEST_STRATEGY = f"{BASE}/select_invest_strategy.png"
    THE_PLANET_OF_FESTIVITIES = f"{BASE}/ThePlanetOfFestivities.png"
    RIGHT = f"{BASE}/right.png"
    PRIMARY_SELECTION = f"{BASE}/primary_selection.png"
    FORTUNE_TELLER = f"{BASE}/FortuneTeller.png"
    RETURN_HIGHEST_RANK = f"{BASE}/return_highest_rank.png"
    JI_MI= f"{BASE}/ji_mi.png"
    CONCLUDE_AND_SETTLE= f"{BASE}/conclude_and_settle.png"
    WITHDRAW_AND_SETTLE = f"{BASE}/withdraw_and_settle.png"
    NEXT_PAGE = f"{BASE}/next_page.png"
    BACK_CURRENCY_WARS = f"{BASE}/back_currency_wars.png"
    RETURN_PREPARATION_PAGE = f"{BASE}/return_preparation_page.png"
    TWO_TWO = f"{BASE}/2-2.png"
    REFRESH_COUNT = f"{BASE}/refresh_count.png"
    REFRESH_COUNT_BTN = f"{BASE}/refresh_count_btn.png"
    RETURN_INVESTMENT_STRATEGY = f"{BASE}/return_investment_strategy.png"
    BATTLE= f"{BASE}/battle.png"
    REFRESH_ENV = f'{BASE}/refresh_environment.png'