//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRAFrontend.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRAFrontend.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessToken.
        /// </summary>
        public static string AccessTokenText {
            get {
                return ResourceManager.GetString("AccessTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ActivityText {
            get {
                return ResourceManager.GetString("ActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Parameters.
        /// </summary>
        public static string AdvancedParametersText {
            get {
                return ResourceManager.GetString("AdvancedParametersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string AdvanceText {
            get {
                return ResourceManager.GetString("AdvanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all configurations.
        /// </summary>
        public static string AllButtonTipText {
            get {
                return ResourceManager.GetString("AllButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Notification.
        /// </summary>
        public static string AllowNotificationText {
            get {
                return ResourceManager.GetString("AllowNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch All.
        /// </summary>
        public static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Address.
        /// </summary>
        public static string ApiAddressText {
            get {
                return ResourceManager.GetString("ApiAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string ApiKeyText {
            get {
                return ResourceManager.GetString("ApiKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Channel.
        /// </summary>
        public static string AppChannelText {
            get {
                return ResourceManager.GetString("AppChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data folder.
        /// </summary>
        public static string AppDataFolder {
            get {
                return ResourceManager.GetString("AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code.
        /// </summary>
        public static string AuthorCodeText {
            get {
                return ResourceManager.GetString("AuthorCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        public static string AutoDetectText {
            get {
                return ResourceManager.GetString("AutoDetectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Set Game Resolution.
        /// </summary>
        public static string AutoResolutionText {
            get {
                return ResourceManager.GetString("AutoResolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string AutoUpdateText {
            get {
                return ResourceManager.GetString("AutoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download and unzip when updates are available.
        /// </summary>
        public static string AutoUpdateTipText {
            get {
                return ResourceManager.GetString("AutoUpdateTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend Launch Arguments.
        /// </summary>
        public static string BackendLaunchArgsText {
            get {
                return ResourceManager.GetString("BackendLaunchArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Opacity.
        /// </summary>
        public static string BackgroundImageOpacityText {
            get {
                return ResourceManager.GetString("BackgroundImageOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImageText {
            get {
                return ResourceManager.GetString("BackgroundImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark API Endpoint.
        /// </summary>
        public static string BarkApiEndpointText {
            get {
                return ResourceManager.GetString("BarkApiEndpointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark Notification (iOS).
        /// </summary>
        public static string BarkNotificationText {
            get {
                return ResourceManager.GetString("BarkNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bark Settings.
        /// </summary>
        public static string BarkSettingsText {
            get {
                return ResourceManager.GetString("BarkSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend logs folder.
        /// </summary>
        public static string BeLogsFolderText {
            get {
                return ResourceManager.GetString("BeLogsFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the image path.
        /// </summary>
        public static string BgImagePathWatermarkText {
            get {
                return ResourceManager.GetString("BgImagePathWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Window.
        /// </summary>
        public static string BorderlessWindowText {
            get {
                return ResourceManager.GetString("BorderlessWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Token.
        /// </summary>
        public static string BotTokenText {
            get {
                return ResourceManager.GetString("BotTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat ID.
        /// </summary>
        public static string ChatIdText {
            get {
                return ResourceManager.GetString("ChatIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string CheckForUpdateText {
            get {
                return ResourceManager.GetString("CheckForUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string CheckText {
            get {
                return ResourceManager.GetString("CheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronicle.
        /// </summary>
        public static string ChronicleText {
            get {
                return ResourceManager.GetString("ChronicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Stamina.
        /// </summary>
        public static string ClearPowerText {
            get {
                return ResourceManager.GetString("ClearPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use StarRail Cloud Game (Experimental).
        /// </summary>
        public static string CloudGameText {
            get {
                return ResourceManager.GetString("CloudGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Recognition Confidence.
        /// </summary>
        public static string ConfidenceText {
            get {
                return ResourceManager.GetString("ConfidenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a config name.
        /// </summary>
        public static string ConfigInputMarkText {
            get {
                return ResourceManager.GetString("ConfigInputMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs folder.
        /// </summary>
        public static string ConfigsFolder {
            get {
                return ResourceManager.GetString("ConfigsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ConsoleText {
            get {
                return ResourceManager.GetString("ConsoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel Opacity.
        /// </summary>
        public static string ControlPanelOpacityText {
            get {
                return ResourceManager.GetString("ControlPanelOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic Strife.
        /// </summary>
        public static string CosmicStrifeText {
            get {
                return ResourceManager.GetString("CosmicStrifeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a desktop shortcut.
        /// </summary>
        public static string CreateShortcutText {
            get {
                return ResourceManager.GetString("CreateShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the currently selected config.
        /// </summary>
        public static string CurrentButtonTipText {
            get {
                return ResourceManager.GetString("CurrentButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current configuration.
        /// </summary>
        public static string CurrentConfigText {
            get {
                return ResourceManager.GetString("CurrentConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Current.
        /// </summary>
        public static string CurrentText {
            get {
                return ResourceManager.GetString("CurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom API Address.
        /// </summary>
        public static string CustomApiAddressText {
            get {
                return ResourceManager.GetString("CustomApiAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkText {
            get {
                return ResourceManager.GetString("DarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Start Page.
        /// </summary>
        public static string DefaultPageText {
            get {
                return ResourceManager.GetString("DefaultPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Options.
        /// </summary>
        public static string DeveloperOptionsText {
            get {
                return ResourceManager.GetString("DeveloperOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Key.
        /// </summary>
        public static string DeviceKeyText {
            get {
                return ResourceManager.GetString("DeviceKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DingTalk Notification.
        /// </summary>
        public static string DingTalkNotificationText {
            get {
                return ResourceManager.GetString("DingTalkNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DingTalk Settings.
        /// </summary>
        public static string DingTalkSettingsText {
            get {
                return ResourceManager.GetString("DingTalkSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Settings.
        /// </summary>
        public static string DiscordSettingsText {
            get {
                return ResourceManager.GetString("DiscordSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Webhook Notification.
        /// </summary>
        public static string DiscordWebhookNotificationText {
            get {
                return ResourceManager.GetString("DiscordWebhookNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayModeText {
            get {
                return ResourceManager.GetString("DisplayModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notification.
        /// </summary>
        public static string EmailNotificationText {
            get {
                return ResourceManager.GetString("EmailNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Developer Options.
        /// </summary>
        public static string EnableDeveloperOptionsText {
            get {
                return ResourceManager.GetString("EnableDeveloperOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Launch Arguments.
        /// </summary>
        public static string EnableGameArgsText {
            get {
                return ResourceManager.GetString("EnableGameArgsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Overlay.
        /// </summary>
        public static string EnableOverlayText {
            get {
                return ResourceManager.GetString("EnableOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Proxy.
        /// </summary>
        public static string EnableProxyText {
            get {
                return ResourceManager.GetString("EnableProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray icon.
        /// </summary>
        public static string EnableTrayIconText {
            get {
                return ResourceManager.GetString("EnableTrayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Key.
        /// </summary>
        public static string EncryptionKeyText {
            get {
                return ResourceManager.GetString("EncryptionKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure.
        /// </summary>
        public static string EnsureText {
            get {
                return ResourceManager.GetString("EnsureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your CDK.
        /// </summary>
        public static string EnterCdkText {
            get {
                return ResourceManager.GetString("EnterCdkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtensionText {
            get {
                return ResourceManager.GetString("ExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let SRA.exe connect to an SRA backend service provided by another machine or another process..
        /// </summary>
        public static string ExternalBackendDescriptionText {
            get {
                return ResourceManager.GetString("ExternalBackendDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feishu AppId.
        /// </summary>
        public static string FeishuAppIdText {
            get {
                return ResourceManager.GetString("FeishuAppIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feishu AppSecret.
        /// </summary>
        public static string FeishuAppSecretText {
            get {
                return ResourceManager.GetString("FeishuAppSecretText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feishu Notification Address.
        /// </summary>
        public static string FeishuNotificationAddressText {
            get {
                return ResourceManager.GetString("FeishuNotificationAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feishu Notification.
        /// </summary>
        public static string FeishuNotificationText {
            get {
                return ResourceManager.GetString("FeishuNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feishu Settings.
        /// </summary>
        public static string FeishuSettingsText {
            get {
                return ResourceManager.GetString("FeishuSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend logs folder.
        /// </summary>
        public static string FeLogsFolder {
            get {
                return ResourceManager.GetString("FeLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        public static string FollowSystemText {
            get {
                return ResourceManager.GetString("FollowSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreenText {
            get {
                return ResourceManager.GetString("FullScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t know what this does, please leave it blank.
        /// </summary>
        public static string GameArgsHintText {
            get {
                return ResourceManager.GetString("GameArgsHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The in-game language needs to be set to Simplified Chinese (简体中文).
        /// </summary>
        public static string GameChineseLanguageTip {
            get {
                return ResourceManager.GetString("GameChineseLanguageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Launch Arguments.
        /// </summary>
        public static string GameLaunchArgumentsText {
            get {
                return ResourceManager.GetString("GameLaunchArgumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string GamePathText {
            get {
                return ResourceManager.GetString("GamePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open On GitHub.
        /// </summary>
        public static string GithubToolTipText {
            get {
                return ResourceManager.GetString("GithubToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SRA.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string GuideText {
            get {
                return ResourceManager.GetString("GuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys in Game.
        /// </summary>
        public static string HotkeysText {
            get {
                return ResourceManager.GetString("HotkeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string IdTypeText {
            get {
                return ResourceManager.GetString("IdTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the End.
        /// </summary>
        public static string InTheEndText {
            get {
                return ResourceManager.GetString("InTheEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightText {
            get {
                return ResourceManager.GetString("LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string LinksText {
            get {
                return ResourceManager.GetString("LinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Path to main.py.
        /// </summary>
        public static string MainPyText {
            get {
                return ResourceManager.GetString("MainPyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapText {
            get {
                return ResourceManager.GetString("MapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Retry Count.
        /// </summary>
        public static string MaxRetryCountText {
            get {
                return ResourceManager.GetString("MaxRetryCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method 1: Group Bot Webhook.
        /// </summary>
        public static string MethodOneText {
            get {
                return ResourceManager.GetString("MethodOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method 2: App API (Can send to specified users).
        /// </summary>
        public static string MethodTwoText {
            get {
                return ResourceManager.GetString("MethodTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chyan.
        /// </summary>
        public static string MirrorChyanText {
            get {
                return ResourceManager.GetString("MirrorChyanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chyan‘s high-speed download service.
        /// </summary>
        public static string MirrorChyanTipText {
            get {
                return ResourceManager.GetString("MirrorChyanTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MirrorChyan.
        /// </summary>
        public static string MirrorText {
            get {
                return ResourceManager.GetString("MirrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to modify.
        /// </summary>
        public static string ModifyHoldText {
            get {
                return ResourceManager.GetString("ModifyHoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New config.
        /// </summary>
        public static string NewConfigText {
            get {
                return ResourceManager.GetString("NewConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Channel.
        /// </summary>
        public static string NotificationChannelText {
            get {
                return ResourceManager.GetString("NotificationChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Group.
        /// </summary>
        public static string NotificationGroupText {
            get {
                return ResourceManager.GetString("NotificationGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Icon.
        /// </summary>
        public static string NotificationIconText {
            get {
                return ResourceManager.GetString("NotificationIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Sound.
        /// </summary>
        public static string NotificationSoundText {
            get {
                return ResourceManager.GetString("NotificationSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Source.
        /// </summary>
        public static string NotificationSourceText {
            get {
                return ResourceManager.GetString("NotificationSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string NotSetText {
            get {
                return ResourceManager.GetString("NotSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneBot QQ Notification.
        /// </summary>
        public static string OneBotNotificationText {
            get {
                return ResourceManager.GetString("OneBotNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneBot Settings.
        /// </summary>
        public static string OneBotSettingsText {
            get {
                return ResourceManager.GetString("OneBotSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OpenText {
            get {
                return ResourceManager.GetString("OpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Show Debug Info.
        /// </summary>
        public static string OverlayDebugInfoText {
            get {
                return ResourceManager.GetString("OverlayDebugInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Address.
        /// </summary>
        public static string ProxyAddressText {
            get {
                return ResourceManager.GetString("ProxyAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Address.
        /// </summary>
        public static string PushAddressText {
            get {
                return ResourceManager.GetString("PushAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Level.
        /// </summary>
        public static string PushLevelText {
            get {
                return ResourceManager.GetString("PushLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Interpreter.
        /// </summary>
        public static string PythonInterpreterText {
            get {
                return ResourceManager.GetString("PythonInterpreterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Number (Group Chat).
        /// </summary>
        public static string QQGroupText {
            get {
                return ResourceManager.GetString("QQGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ Number (Private Chat).
        /// </summary>
        public static string QQPrivateText {
            get {
                return ResourceManager.GetString("QQPrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string ReceiverEmailAddrText {
            get {
                return ResourceManager.GetString("ReceiverEmailAddrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Rewards.
        /// </summary>
        public static string ReceiveRewardsText {
            get {
                return ResourceManager.GetString("ReceiveRewardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver ID.
        /// </summary>
        public static string ReceiverIdText {
            get {
                return ResourceManager.GetString("ReceiverIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string RegularText {
            get {
                return ResourceManager.GetString("RegularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Window Size and Position.
        /// </summary>
        public static string RememberWindowSizeText {
            get {
                return ResourceManager.GetString("RememberWindowSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, SRA will remember the window&apos;s position and size, and restore them on next startup.
        /// </summary>
        public static string RememberWindowSizeTipText {
            get {
                return ResourceManager.GetString("RememberWindowSizeTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Server Address.
        /// </summary>
        public static string RemoteServerAddressText {
            get {
                return ResourceManager.GetString("RemoteServerAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current config.
        /// </summary>
        public static string RemoveConfigText {
            get {
                return ResourceManager.GetString("RemoveConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource integrity check.
        /// </summary>
        public static string ResourceIntegrityCheckText {
            get {
                return ResourceManager.GetString("ResourceIntegrityCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry After Task Failure.
        /// </summary>
        public static string RetryAfterTaskFailureText {
            get {
                return ResourceManager.GetString("RetryAfterTaskFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OCR Image.
        /// </summary>
        public static string SaveOcrImageText {
            get {
                return ResourceManager.GetString("SaveOcrImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data only without running.
        /// </summary>
        public static string SaveOnlyButtonTipText {
            get {
                return ResourceManager.GetString("SaveOnlyButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Only.
        /// </summary>
        public static string SaveOnlyText {
            get {
                return ResourceManager.GetString("SaveOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string SenderEmailAddrText {
            get {
                return ResourceManager.GetString("SenderEmailAddrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendKey.
        /// </summary>
        public static string SendKeyText {
            get {
                return ResourceManager.GetString("SendKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Screenshot.
        /// </summary>
        public static string SendScreenshotText {
            get {
                return ResourceManager.GetString("SendScreenshotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerChan WeChat Notification.
        /// </summary>
        public static string ServerChanNotificationText {
            get {
                return ResourceManager.GetString("ServerChanNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerChan Settings.
        /// </summary>
        public static string ServerChanSettingsText {
            get {
                return ResourceManager.GetString("ServerChanSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SettingText {
            get {
                return ResourceManager.GetString("SettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Secret.
        /// </summary>
        public static string SignSecretText {
            get {
                return ResourceManager.GetString("SignSecretText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SmtpPortText {
            get {
                return ResourceManager.GetString("SmtpPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        public static string SmtpServerText {
            get {
                return ResourceManager.GetString("SmtpServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Settings.
        /// </summary>
        public static string SmtpSettingsText {
            get {
                return ResourceManager.GetString("SmtpSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string SourceRepositoryText {
            get {
                return ResourceManager.GetString("SourceRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string SponsorText {
            get {
                return ResourceManager.GetString("SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRA Official Website.
        /// </summary>
        public static string SraWebsiteText {
            get {
                return ResourceManager.GetString("SraWebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the task in the current mode.
        /// </summary>
        public static string StartButtonTipText {
            get {
                return ResourceManager.GetString("StartButtonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGameText {
            get {
                return ResourceManager.GetString("StartGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Up.
        /// </summary>
        public static string StartUpText {
            get {
                return ResourceManager.GetString("StartUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Hotkey.
        /// </summary>
        public static string StopHotkeyText {
            get {
                return ResourceManager.GetString("StopHotkeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Notification.
        /// </summary>
        public static string SystemNotificationText {
            get {
                return ResourceManager.GetString("SystemNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify on Task Complete.
        /// </summary>
        public static string TaskCompleteNotificationText {
            get {
                return ResourceManager.GetString("TaskCompleteNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Complete.
        /// </summary>
        public static string TaskCompleteText {
            get {
                return ResourceManager.GetString("TaskCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TaskNameText {
            get {
                return ResourceManager.GetString("TaskNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Notification Configuration.
        /// </summary>
        public static string TaskNotificationConfigText {
            get {
                return ResourceManager.GetString("TaskNotificationConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Settings.
        /// </summary>
        public static string TaskSettingsText {
            get {
                return ResourceManager.GetString("TaskSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify on Task Start.
        /// </summary>
        public static string TaskStartNotificationText {
            get {
                return ResourceManager.GetString("TaskStartNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        public static string TechniqueText {
            get {
                return ResourceManager.GetString("TechniqueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Notification.
        /// </summary>
        public static string TelegramNotificationText {
            get {
                return ResourceManager.GetString("TelegramNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Settings.
        /// </summary>
        public static string TelegramSettingsText {
            get {
                return ResourceManager.GetString("TelegramSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Safety.
        /// </summary>
        public static string ThreadSafetyText {
            get {
                return ResourceManager.GetString("ThreadSafetyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailblaze Power.
        /// </summary>
        public static string TrailblazePowerText {
            get {
                return ResourceManager.GetString("TrailblazePowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannelText {
            get {
                return ResourceManager.GetString("UpdateChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game Using CMD.
        /// </summary>
        public static string UseCmdLaunchText {
            get {
                return ResourceManager.GetString("UseCmdLaunchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use External SRA Backend.
        /// </summary>
        public static string UseExternalBackendText {
            get {
                return ResourceManager.GetString("UseExternalBackendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group (QQ).
        /// </summary>
        public static string UserGroupText {
            get {
                return ResourceManager.GetString("UserGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Python to run the backend.
        /// </summary>
        public static string UsingPythonText {
            get {
                return ResourceManager.GetString("UsingPythonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp.
        /// </summary>
        public static string WarpText {
            get {
                return ResourceManager.GetString("WarpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Notification.
        /// </summary>
        public static string WebhookNotificationText {
            get {
                return ResourceManager.GetString("WebhookNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Settings.
        /// </summary>
        public static string WebhookSettingsText {
            get {
                return ResourceManager.GetString("WebhookSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Official Website.
        /// </summary>
        public static string WebsiteToolTipText {
            get {
                return ResourceManager.GetString("WebsiteToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeCom Notification.
        /// </summary>
        public static string WeComNotificationText {
            get {
                return ResourceManager.GetString("WeComNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeCom Settings.
        /// </summary>
        public static string WeComSettingsText {
            get {
                return ResourceManager.GetString("WeComSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowedText {
            get {
                return ResourceManager.GetString("WindowedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSizeText {
            get {
                return ResourceManager.GetString("WindowSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xxtui Notification.
        /// </summary>
        public static string XxtuiNotificationText {
            get {
                return ResourceManager.GetString("XxtuiNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xxtui Settings.
        /// </summary>
        public static string XxtuiSettingsText {
            get {
                return ResourceManager.GetString("XxtuiSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomText {
            get {
                return ResourceManager.GetString("ZoomText", resourceCulture);
            }
        }
    }
}
