name: auto-mas.yml
on:
  workflow_dispatch:

jobs:
  auto_mas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Auto-MAS
        run: |
          VERSION=$(node -p '"v" + require("./package.json").version')
          CHANNEL=$([[ "$VERSION" == *"-beta"* ]] && echo "beta" || echo "stable")
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"version\":\"$VERSION\",\"res_id\":\"StarRailAssistant\",\"channel\":\"$CHANNEL\"}" \
            "${{ secrets.UPDATE_URL }}"